### ISSUE TITLE
Failing to find booking slots

### ISSUE THREAD

**Issue by dalder1** [jeffknaide/resy-bot#11]
```
poetry run python main.py .\credentials.json .\reservation-request.json
INFO:__main__:waiting for drop time!
INFO:resy_bot.api_access:2024-07-25T22:21:03.113557 Sending request to find booking slots
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.resy.com:443
DEBUG:urllib3.connectionpool:https://api.resy.com:443 "GET /4/find?lat=0&long=0&day=2024-08-08&party_size=2&venue_id=72298 HTTP/1.1" 500 21
INFO:resy_bot.api_access:2024-07-25T22:21:03.750415 Received response for
Traceback (most recent call last):
  File "C:\Projects\resy\resy-bot\main.py", line 40, in <module>
    wait_for_drop_time(args.resy_config_path, args.reservation_config_path)
  File "C:\Projects\resy\resy-bot\main.py", line 26, in wait_for_drop_time
    return manager.make_reservation_at_opening_time(timed_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\resy\resy-bot\resy_bot\manager.py", line 128, in make_reservation_at_opening_time
    return self.make_reservation_with_retries(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\resy\resy-bot\resy_bot\manager.py", line 90, in make_reservation_with_retries
    return self.make_reservation(reservation_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\resy\resy-bot\resy_bot\manager.py", line 61, in make_reservation
    slots = self.api_access.find_booking_slots(body)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\resy\resy-bot\resy_bot\api_access.py", line 79, in find_booking_slots
    raise HTTPError(
requests.exceptions.HTTPError: Failed to find booking slots: 500, Internal Server Error
PS C:\Projects\resy\resy-bot> poetry run python main.py .\credentials.json .\reservation-request.json
INFO:__main__:waiting for drop time!
INFO:resy_bot.manager:time reached, making a reservation now! 2024-07-25 22:21:59.731362
INFO:resy_bot.api_access:2024-07-25T22:21:59.734843 Sending request to find booking slots
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.resy.com:443
DEBUG:urllib3.connectionpool:https://api.resy.com:443 "GET /4/find?lat=0&long=0&day=2024-08-08&party_size=2&venue_id=72298 HTTP/1.1" 500 21
INFO:resy_bot.api_access:2024-07-25T22:22:00.376351 Received response for 
Traceback (most recent call last):
  File "C:\Projects\resy\resy-bot\main.py", line 40, in <module>
    wait_for_drop_time(args.resy_config_path, args.reservation_config_path)
  File "C:\Projects\resy\resy-bot\main.py", line 26, in wait_for_drop_time
    return manager.make_reservation_at_opening_time(timed_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\resy\resy-bot\resy_bot\manager.py", line 128, in make_reservation_at_opening_time
    return self.make_reservation_with_retries(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\resy\resy-bot\resy_bot\manager.py", line 90, in make_reservation_with_retries
    return self.make_reservation(reservation_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\resy\resy-bot\resy_bot\manager.py", line 61, in make_reservation
    slots = self.api_access.find_booking_slots(body)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\resy\resy-bot\resy_bot\api_access.py", line 79, in find_booking_slots
    raise HTTPError(
requests.exceptions.HTTPError: Failed to find booking slots: 500, Internal Server Error
```

Could this be a similar issue to https://github.com/jeffknaide/resy-bot/issues/3 ?

**Comment by Blk836** [comment]
Update headers to include these other ones:
`    headers = {
        "Authorization": config.get_authorization(),
        "X-Resy-Auth-Token": config.token,
        "X-Resy-Universal-Auth": config.token,
        "Origin": "https://resy.com",
        "X-origin": "https://resy.com",
        "Referrer": "https://resy.com/",
        "Accept": "application/json, text/plain, */*",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0",  # Browser User-Agent
        "Cache-Control": "no-cache",  # Cache-Control header
    }`
