### ISSUE TITLE
Failing to book reservation that is known to be available

### ISSUE THREAD

**Issue by davidhildebrand** [jeffknaide/resy-bot#3]
To initially test resy-bot, I tried to book a reservation slot that I know is open from looking on Resy.  Unfortunately, the booking fails.
It's likely that I'm just doing something wrong, but I'm not sure what. 

For example, I tried to book a reservation for a time around 12pm on Saturday 15 April at NR (upper east side, NYC; https://resy.com/cities/ny/nr?date=2023-04-15&seats=2).

The restaurant appears to have availability during this time:
<img width="815" alt="NR_screenshot" src="https://user-images.githubusercontent.com/799157/231031562-9cd05fb0-b16f-44ef-a11a-b835b6846fb3.png">

My `credentials.json` configuration was formatted as recommended.
My `request.json` configuration was:
```
{
"reservation_request": {
  "party_size": 2,
  "venue_id": 39797,
  "window_hours": 1,
  "prefer_early": false,
  "ideal_date": "2023-04-15",
  "ideal_hour": 12,
  "ideal_minute": 0,
  "preferred_type": "Dining Room"
},
  "expected_drop_hour": "11",
  "expected_drop_minute": "35"
}
```

Upon running the bot, here is the output:
```
INFO:__main__:waiting for drop time!
INFO:resy_bot.manager:time reached, making a reservation now! 2023-04-12 11:34:59.999906
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.resy.com:443
DEBUG:urllib3.connectionpool:https://api.resy.com:443 "GET /4/find?venue_id=39797&party_size=2&day=2023-04-15&lat=0&long=0 HTTP/1.1" 200 None
INFO:resy_bot.manager:17
INFO:resy_bot.manager:[Slot(config=SlotConfig(id='847831', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/12:00:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 12, 0), end=datetime.datetime(2023, 4, 15, 14, 0))), Slot(config=SlotConfig(id='847831', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/12:15:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 12, 15), end=datetime.datetime(2023, 4, 15, 14, 15))), Slot(config=SlotConfig(id='847831', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/12:30:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 12, 30), end=datetime.datetime(2023, 4, 15, 14, 30))), Slot(config=SlotConfig(id='847831', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/12:45:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 12, 45), end=datetime.datetime(2023, 4, 15, 14, 45))), Slot(config=SlotConfig(id='847831', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/13:00:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 13, 0), end=datetime.datetime(2023, 4, 15, 15, 0))), Slot(config=SlotConfig(id='847831', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/13:15:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 13, 15), end=datetime.datetime(2023, 4, 15, 15, 15))), Slot(config=SlotConfig(id='847831', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/13:30:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 13, 30), end=datetime.datetime(2023, 4, 15, 15, 30))), Slot(config=SlotConfig(id='847831', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/13:45:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 13, 45), end=datetime.datetime(2023, 4, 15, 15, 45))), Slot(config=SlotConfig(id='652488', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/14:00:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 14, 0), end=datetime.datetime(2023, 4, 15, 16, 0))), Slot(config=SlotConfig(id='652488', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/14:15:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 14, 15), end=datetime.datetime(2023, 4, 15, 16, 15))), Slot(config=SlotConfig(id='652488', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/14:30:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 14, 30), end=datetime.datetime(2023, 4, 15, 16, 30))), Slot(config=SlotConfig(id='652489', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/14:45:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 14, 45), end=datetime.datetime(2023, 4, 15, 16, 45))), Slot(config=SlotConfig(id='652489', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/15:00:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 15, 0), end=datetime.datetime(2023, 4, 15, 17, 0))), Slot(config=SlotConfig(id='652491', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/15:15:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 15, 15), end=datetime.datetime(2023, 4, 15, 17, 15))), Slot(config=SlotConfig(id='652491', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/15:30:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 15, 30), end=datetime.datetime(2023, 4, 15, 17, 30))), Slot(config=SlotConfig(id='652491', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/15:45:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 15, 45), end=datetime.datetime(2023, 4, 15, 17, 45))), Slot(config=SlotConfig(id='652491', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/16:00:00/2/Dining Room'), date=SlotDate(start=datetime.datetime(2023, 4, 15, 16, 0), end=datetime.datetime(2023, 4, 15, 18, 0)))]
INFO:resy_bot.manager:config=SlotConfig(id='847831', type='Dining Room', token='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/12:00:00/2/Dining Room') date=SlotDate(start=datetime.datetime(2023, 4, 15, 12, 0), end=datetime.datetime(2023, 4, 15, 14, 0))
INFO:resy_bot.manager:config_id='rgs://resy/39797/920265/1/2023-04-15/2023-04-15/12:00:00/2/Dining Room' party_size=2 day='2023-04-15'
DEBUG:urllib3.connectionpool:https://api.resy.com:443 "GET /3/details?config_id=rgs%3A%2F%2Fresy%2F39797%2F920265%2F1%2F2023-04-15%2F2023-04-15%2F12%3A00%3A00%2F2%2FDining+Room&party_size=2&day=2023-04-15 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.resy.com:443 "POST /3/book HTTP/1.1" 500 21
Traceback (most recent call last):
  File "/home/davidh/Repositories/resy-bot/main.py", line 39, in <module>
    wait_for_drop_time(args.resy_config_path, args.reservation_config_path)
  File "/home/davidh/Repositories/resy-bot/main.py", line 25, in wait_for_drop_time
    return manager.make_reservation_at_opening_time(timed_request)
  File "/home/davidh/Repositories/resy-bot/resy_bot/manager.py", line 128, in make_reservation_at_opening_time
    return self.make_reservation_with_retries(
  File "/home/davidh/Repositories/resy-bot/resy_bot/manager.py", line 91, in make_reservation_with_retries
    return self.make_reservation(reservation_request)
  File "/home/davidh/Repositories/resy-bot/resy_bot/manager.py", line 80, in make_reservation
    resy_token = self.api_access.book_slot(booking_request)
  File "/home/davidh/Repositories/resy-bot/resy_bot/api_access.py", line 105, in book_slot
    raise HTTPError(f"Failed to book slot: {resp.status_code}, {resp.text}")
requests.exceptions.HTTPError: Failed to book slot: 500, Internal Server Error
```

Any help would be greatly appreciated.

**Comment by jeffknaide** [comment]
Hi @davidhildebrand - looks like they changed the expected headers. I just updated the Session to include the new `origin` header, which appears to resolve the issue on my end. let me know if you are still having issues.
